### ISSUE TITLE
IOS app is asking for new plugin 1.7 

### ISSUE THREAD

**Issue by pmbroth** [MoonshineSG/OctoPrint-Mobile#22]
Hello,

I have installed the latest plugin - 1.6.5.  The IOS app is wanting new plug in 1.7.  I cannot find it anywhere.

Thank you

Brian

**Comment by DaveHerm** [comment]
Hi,

the same for me, do get the message to update to 1.7 but the latest release is 1.6.5
please upload the new release

br
thomas

**Comment by MoonshineSG** [comment]
iOS app release was , by mistake set to auto instead of manual, so once approved it was published.
The plugin was all prepared but not released and I had to fly off (literally)

I re-coded a quick fix of version 1.7 on my iPhone while transferring from airport to hotel :) another rushed job. Please let me know if it works.

**Comment by pmbroth** [comment]
That fixed it thank you!

**Comment by DaveHerm** [comment]
can approve that it works for me too

thank you

**Comment by MoonshineSG** [comment]
Glad to hear it's ok. 

Leave a positive review on AppStore if you enjoy the plugin. Thanks.
