### ISSUE TITLE
How do I enable Octoprint Switch in my code?

### ISSUE THREAD

**Issue by Raymosj** [MoonshineSG/OctoPrint-Mobile#25]
Hi There,

I love your program. I wanted to know how I add octoprint switch to Nautilus? I really want that functionality. I'm clueless after reading the octoprint switch github site. DO I need to add code? What code? Where? Thankss so much for the great support.....

**Comment by 1n5aN1aC** [comment]
No, you should not need to edit code yourself...

You will need to install the separate "Octoprint-Switch" plugin in your Octoprint, then edit the config and tell it which pins you have connected the printers power to, lights, etc.

**Comment by Raymosj** [comment]
is there any instructions on doing it anywhere?

**Comment by 1n5aN1aC** [comment]
Follow the instructions [here](https://github.com/MoonshineSG/OctoPrint-Mobile/wiki/Install), but instead of using that URL, use the one for [Octoprint-Switch](https://github.com/MoonshineSG/OctoPrint-Switch) which is ```https://github.com/MoonshineSG/Octoprint-Switch/archive/master.zip```

Once it's installed, the readme [on the Octoprint-Switch page](https://github.com/MoonshineSG/OctoPrint-Switch) explains the configuration options.

**Comment by Raymosj** [comment]
thanks so much.....

**Comment by MoonshineSG** [comment]
@1n5aN1aC is right. There should be no need to edit code. 

@1n5aN1aC, just curious.. are you using the Switch as well?

**Comment by 1n5aN1aC** [comment]
Not yet, but I plan to when I have the chance to set it up again.

**Comment by MoonshineSG** [comment]
Once you enable the Switch plugin, the 4 additional functions will be available on OctoPrint as well as Nautilus.
