### ISSUE TITLE
Multiple Printers

### ISSUE THREAD

**Issue by S4ndr** [MoonshineSG/OctoPrint-Mobile#37]
Hello, 
i wan't to get this app but is it possible to add multiple printers at once and switch between them?
Thanks!

**Comment by MoonshineSG** [comment]
Hi. No, you can only setup one printer. 

I have a "work in progress" version with which I'm trying to  find a way to support multiple printers but it will be a while until it's ready for release. Mostly because it's not really a priority for me - I only have a single printer. But that doesn't mean i am not working on it.

**Comment by S4ndr** [comment]
Hello, 
That would be awesome if u can get it! The app looks great and i think i am gonna get it, hope u can figure it out!

**Comment by stofakiller** [comment]
I'm also looking for this feature, i have 3 printers with octoprint

**Comment by MoonshineSG** [comment]
glad to see that my work will have some use... 
it proves to be slightly more work that I initially anticipated but it's moving forward ... 

btw, it will not be "multi printer monitoring" but "multi printer config" with easy switch between them...

**Comment by MoonshineSG** [comment]
the multi printer support is ready. just pending approval from Apple.

**Comment by stofakiller** [comment]
Great, looking forward to try it

**Comment by MoonshineSG** [comment]
it took way longer than i expected... (could be because I'm not familiar with objective c ? )
