### ISSUE TITLE
iPhone X Display issues

### ISSUE THREAD

**Issue by trendelkamp** [MoonshineSG/OctoPrint-Mobile#62]
Hi,

on an iPhoneX the Display is not utilized 100% correct. 
In menus icons are cut a little bit on the sides. 
More of an issue is the scaling of the webcam stream. This is streched. 
Please see the attached screenshots. 

Thanks
![img_0033](https://user-images.githubusercontent.com/12778148/34643143-8d0360b8-f31f-11e7-8fa9-f48de1b768d0.JPG)
![img_0034](https://user-images.githubusercontent.com/12778148/34643144-8d1e0c2e-f31f-11e7-9e7b-ea877c9302d4.JPG)
![img_01321](https://user-images.githubusercontent.com/12778148/34643166-c9c2dcfe-f31f-11e7-9b6a-dc0cd8392607.png)

**Comment by MoonshineSG** [comment]
in order to maximise the usable UI, the icons have to suffer a little (so it's on purpose like that!) ... nothing really that affects usability... when apple removes that notch, you will be able to see the full icons...

as for the camera, it is "fit" mode on height - so you can see whole image, but if you tap on it it changes to "full screen" and follows the camera proportions and allows pinch to zoom... (tap again to go back to the menu mode)

**Comment by MoonshineSG** [comment]
I did some minor changes to deal with some UI issues under X... update to 1.20 and have a look

**Comment by trendelkamp** [comment]
Looks superb after the update! Thanks
For the camera, didn´t know tapping on the screen hasn an effect with the camera... ;)

Case closed

**Comment by MoonshineSG** [comment]
Btw, if you enjoy Nautilus, a positive review on AppStore would be much appreciated. Thanks.
